parameters:
  tipoUsuario:
    administrador: 1
    acreditador: 2
    delegacion: 3

twig:
  globals:
    tipoUsuario:
      administrador: 1
      acreditador: 2
      delegacion: 3
    rutabasedocumentos: /sisweb/eventosdeportivos/web/

#rutabasedocumentosDev:  /sudamericanos_juveniles/web/
#rutabasedocumentosProd: /sisweb/eventosdeportivos/web/