# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_db_provider:
            entity:
                class: SudJuvenilesBundle:Usuarios
                property: username

    encoders:
        #AkademiaBundle\Entity\Usuarios:
            #algorithm: bcrypt
        Symfony\component\Security\Core\User\User: plaintext
        SudJuvenilesBundle\Entity\Usuarios: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        sudamericanos_juveniles:
            anonymous: ~
            pattern: ^/
            provider: user_db_provider

            form_login:
                login_path: /login
                check_path: /login
                default_target_path: panel-general

            http_basic: ~
            logout:
                path: /logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - {path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^(/panel), roles: [ROLE_ADMIN]}