<?php

namespace SudJuvenilesBundle\Repository;

/**
 * AsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAsignaciones(){

        try {

            $query="    SELECT id asignacionId,nombre asignacionNombre from asignacion WHERE estado=1";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $asignaciones = $stmt->fetchAll();

            return $asignaciones;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }
}
