<?php

namespace SudJuvenilesBundle\Repository;

/**
 * ConfiguracionVacantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionVacantesRepository extends \Doctrine\ORM\EntityRepository
{
}
