<?php

namespace SudJuvenilesBundle\Repository;

/**
 * DisciplinaDelegacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaDelegacionRepository extends \Doctrine\ORM\EntityRepository
{
}
