<?php

namespace SudJuvenilesBundle\Repository;

/**
 * DisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\DBAL\DBALException;

class DisciplinaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDisciplinas($periodoActivoId){

        try {

            $query="  SELECT *FROM disciplina";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $disciplinas = $stmt->fetchAll();

            return $disciplinas;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }

    }

    public function getModalidades(){

        try {

            $query="    SELECT id modalidadId,disciplina_id disciplinaId,nombre modalidadNombre from modalidad WHERE estado=1";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $modalidades = $stmt->fetchAll();

            return $modalidades;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

    public function getDivisiones(){

        try {

            $query="    SELECT id divisionId,disciplina_id disciplinaId,nombre divisionNombre from divisiones WHERE estado=1";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $divisiones = $stmt->fetchAll();

            return $divisiones;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

}
