<?php

namespace SudJuvenilesBundle\Repository;

/**
 * GaleriaVideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaVideosRepository extends \Doctrine\ORM\EntityRepository
{


    public function modificarVideoGaleria($videoGaleriaId,$linkVideo,$usuario ,$fechaVideo){
            
        try {

            $query=" EXEC modificarVideoGaleria '$linkVideo','$fechaVideo','$usuario',$videoGaleriaId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoModificacion = $stmt->fetchAll();

            return $estadoModificacion[0]['estadoModificacion'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

	public function registrarVideoGaleria($linkVideo,$fechaVideo, $usuarioId, $periodoId ){
        
        try {
            $query=" EXEC registrarVideosGaleria '$linkVideo','$fechaVideo', $usuarioId, $periodoId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoRegistro = $stmt->fetchAll();

            return $estadoRegistro[0]['estadoRegistro'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

	public function mostrarVideosGaleria($periodoActivoId){
        
        try {

            $query=" SELECT 
            id,
            video_url,
            CONVERT(DATE,fecha_grabo_video,101) fecha_grabo_video
            FROM galeria_videos WHERE estado=1 AND periodo_id = $periodoActivoId
            ORDER BY fecha_grabo_video DESC;";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $videos = $stmt->fetchAll();

            return $videos;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

    public function eliminarVideoGaleria($galeriaVideoId,$usuarioId){

        try {

            $query="UPDATE galeria_videos SET estado = 0,fecha_modifico=getDate() , usuario_modifico = $usuarioId WHERE id = $galeriaVideoId ";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();

            return 1;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }       
    }

     public function obtenerVideoGaleria($id){
        
        try {
            $query="    SELECT 
                        id,
                        CONVERT(date,fecha_grabo_video,101) fecha_grabo_video,
                        video_url
                        FROM galeria_videos
                        where estado=1 AND id=$id;";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $video = $stmt->fetchAll();

            return $video;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

}
