<?php

namespace SudJuvenilesBundle\Repository;

/**
 * GaleriaResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaResultadosRepository extends \Doctrine\ORM\EntityRepository
{

    public function eliminarResultadoGaleria($galeriaResultId,$usuarioId){
        
        try {

            $query="UPDATE galeria_resultados SET estado = 0,fecha_modificacion=getDate() , usuario_modifico=$usuarioId WHERE id = $galeriaResultId ";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();

            return 1;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }


	public function registrarResultadoGaleria($tituloResultado,$fechaResultado,$rutaResultadoAll,$usuario,$resultadoDescripcion,$disciplinaResultado){
        
        try {

            $query=" EXEC registrarResultadoGaleria '$tituloResultado','$fechaResultado','$rutaResultadoAll','$usuario','$resultadoDescripcion',$disciplinaResultado";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoRegistro = $stmt->fetchAll();

            return $estadoRegistro[0]['estadoRegistro'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }


    public function modificarResultadoGaleria($tituloResultado,$fechaResultado,$rutaResultadoAll,$usuario,$resultadoDescripcion,$disciplinaResultado,$resultadoGaleriaId){
        
        try {

            $query=" EXEC modificarResultadoGaleria '$tituloResultado','$fechaResultado','$rutaResultadoAll','$usuario','$resultadoDescripcion',$disciplinaResultado,$resultadoGaleriaId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoModificacion = $stmt->fetchAll();

            return $estadoModificacion[0]['estadoModificacion'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }


    public function obtenerResultadoGaleria($galeriaResultId){

        try {
            $query=" SELECT 
                    galResult.id galResultId,
                    galResult.titulo titulo,
                    galResult.foto_url,
                    galResult.descripcion_foto,
                    dis.nombre disciplina,
                    dis.id disciplinaId,
                    CONVERT(date,galResult.fecha_tomo_foto,101) fecha_tomo_foto
                    FROM galeria_resultados galResult
                    INNER JOIN disciplina dis ON dis.id = galResult.disciplina_id
                    WHERE galResult.estado=1 AND galResult.id = $galeriaResultId 
                    ORDER BY galResult.fecha_tomo_foto DESC";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $resultado = $stmt->fetchAll();

            return $resultado;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

	public function mostrarResultadosGaleria(){
        
        try {
            $query=" SELECT 
                    galResult.id galResultId,
					galResult.titulo titulo,
					galResult.foto_url,
					galResult.descripcion_foto,
					dis.nombre disciplina,
                    dis.id disciplinaId,
					CONVERT(date,galResult.fecha_tomo_foto,101) fecha_tomo_foto
					FROM galeria_resultados galResult
					INNER JOIN disciplina dis ON dis.id = galResult.disciplina_id
                    WHERE galResult.estado=1
					ORDER BY galResult.fecha_tomo_foto DESC";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $resultados = $stmt->fetchAll();

            return $resultados;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }
}
