<?php

namespace SudJuvenilesBundle\Repository;

/**
 * GaleriaFotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\DBAL\DBALException;

class GaleriaFotosRepository extends \Doctrine\ORM\EntityRepository
{


    public function modificarFotoGaleria($tituloModificar,$fechaModificar,$rutaModificarAll,$usuario,$modificarDescripcion,$modificarGaleriaId){
            

        try {

            $query=" EXEC modificarFotoGaleria '$tituloModificar','$fechaModificar','$rutaModificarAll','$usuario','$modificarDescripcion',$modificarGaleriaId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoModificacion = $stmt->fetchAll();

            return $estadoModificacion[0]['estadoModificacion'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

    public function eliminarFotoGaleria($galeriaResultId,$usuarioId){
        
        try {

            $query="UPDATE galeria_fotos SET estado = 0,fecha_actualizacion=getDate() , usuario_modifico=$usuarioId WHERE id = $galeriaResultId ";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();

            return 1;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

	public function registrarFotoGaleria($tituloFoto,$fechaFoto, $rutaFotoAll,$usuario,$fotoDescripcion,$periodoId){
        
        try {

            $query=" EXEC registrarFotosGaleria '$tituloFoto','$fechaFoto','$rutaFotoAll','$usuario','$fotoDescripcion',$periodoId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $estadoRegistro = $stmt->fetchAll();

            return $estadoRegistro[0]['estadoRegistro'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

	 public function mostrarFotoGaleria($periodoActivoId){
        
        try {
            $query=" SELECT *FROM galeria_fotos WHERE estado=1 AND periodo_id = $periodoActivoId";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $fotos = $stmt->fetchAll();

            return $fotos;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

     public function obtenerResultadoGaleria($id){
        
        try {
            $query="    SELECT 
                        id,
                        titulo,
                        foto_url,
                        CONVERT(date,fecha_tomo_foto,101) fecha_tomo_foto,
                        descripcion_foto  
                        FROM galeria_fotos
                        where estado=1 AND id=$id;";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $foto = $stmt->fetchAll();

            return $foto;

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

}
