<?php

namespace SudJuvenilesBundle\Repository;

/**
 * InscripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
