<?php

namespace SudJuvenilesBundle\Repository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\DBAL\DBALException;

class PaisRepository extends \Doctrine\ORM\EntityRepository
{

	public function getPaises(){
		try {
            $query=" SELECT *FROM pais ORDER BY nombre;";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $paises = $stmt->fetchAll();

            return $paises;
            
        }catch (DBALException $e) {
          	$message = $e->getCode();
            return $message;
    	}
	}

}
