<?php

namespace SudJuvenilesBundle\Repository;

/**
 * ParticipanteAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipanteAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
