<?php

namespace SudJuvenilesBundle\Repository;

/**
 * PeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getIdPeriodoActivo(){

        try {

            $query="   SELECT TOP 1 *FROM periodo WHERE estado=1";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $periodoActivoId = $stmt->fetchAll();

            return $periodoActivoId[0]['id'];

        }catch (DBALException $e) {
            $message = $e->getCode();
            return $message;
        }
    }

}
