<?php

namespace SudJuvenilesBundle\Repository;

/**
 * TipoParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoParticipanteRepository extends \Doctrine\ORM\EntityRepository
{
}
