<?php

namespace SudJuvenilesBundle\Repository;

/**
 * TipoParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoParticipanteRepository extends \Doctrine\ORM\EntityRepository
{

	public function getTipoParticipanteAll(){

      $query="SELECT *FROM tipo_participante";
               
      $stmt = $this->getEntityManager()->getConnection()->prepare($query);
      $stmt->execute();
      $tipoParticipantes = $stmt->fetchAll();

      return $tipoParticipantes;
  }

}
