<?php

namespace SudJuvenilesBundle\Repository;

/**
 * TipoGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
